name: Build and Release Godot game

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      build_targets:
        description: 'Build desktop targets?'
        required: false
        default: 'true'
      deploy_pages:
        description: 'Deploy to GitHub Pages?'
        required: false
        default: 'true'
permissions:
  contents: write
  pages: write

jobs:
  export_game:
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.build_targets == 'true' }}
    runs-on: ubuntu-latest
    permissions: write-all
    name: Export Game (Desktop)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Export game
        id: export
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot-builds/releases/download/4.4.1-stable/Godot_v4.4.1-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true
          presets_to_export: 'windows-x86_64, linux-x86_64'

      - name: Create release
        uses: ncipollo/release-action@v1.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          tag: ${{ github.ref_name }}
          artifacts: ${{ steps.export.outputs.archive_directory }}/*
  export_web:
    runs-on: ubuntu-latest
    name: Export Web (HTML5)
    container:
      image: barichello/godot-ci:4.4.1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup export templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/4.4.1.stable ~/.local/share/godot/export_templates/4.4.1.stable
      - name: Export to HTML5
        run: |
          mkdir -p build/web
          godot --headless --verbose --export-release "web-standalone-pc" "build/web/index.html"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: gh-pages
          force_orphan: true
          keep_files: false
          destination_dir: .
          commit_message: 'Deploy Web version from GitHub Actions'